language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
install:
  - npm install -g npm
  - npm install
  - node cli.js tls https://example.com -n=example.com -k
cache:
  directories:
    - node_modules
